//Making a variable to call the id "generate" from the html
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");
  passwordText.value = password;

}

/*This function is used to generate a random lowercase letter using the function "Math.random" 
to generate a random number between 97 and 122 and correlate it to the charcode using 
"String.fromCharCode". I have also used the function "Math.floor" in order to round the 
integer generated by "Math.random" to the nearest full number.*/
function lowerGen(){
  return String.fromCharCode(Math.floor(Math.random() * 26) + 97);
 
}
console.log(lowerGen())


/*This function is used to generate a random uppercase letter using the function "Math.random" 
to generate a random number between 65 and 90 and to correlate it to the charcode using 
"String.fromCharCode". I have also used the function "Math.floor" in order to round the 
integer generated by "Math.random" to the nearest full number.*/
function upperGen(){
  return String.fromCharCode(Math.floor(Math.random() * 26) + 65);
  
}
console.log(upperGen())


/*This function is used to generate a random integer using the function "Math.random" 
to generate a random number between 48 and 57 to correlate it to the charcode using 
"String.fromCharCode". I have also used the function "Math.floor" in order to round the 
integer generated by "Math.random" to the nearest full number.*/
function integerGen(){
  return String.fromCharCode(Math.floor(Math.random() * 10) + 48);
  
}
console.log(integerGen( ))


/*This function is used to generate a random lowercase letter using the function "Math.random" 
to generate a random number between 97 and 122 to correlate it to the charcode using 
"String.fromCharCode". I have also used the function Math.floor in order to round the 
integer generated by Math.random to the nearest full number.*/
function symbolGen(){
  return String.fromCharCode(Math.floor(Math.random() * 12) + 35);
  

  
}
console.log(symbolGen())

function generatePassword(){
 
}


