//Making a variable to call the id "generate" from the html
var generateBtn = document.querySelector("#generate");

function randomNum(min, max){
 if (!max) {
  max = min
  min = 0
 }
 var rand = Math.random()
 return Math.floor(min*(1 - rand) + rand*max)
}

function randomItem(list) {
  return list[randomNum(list.length)]
}

function generatePassword(){
  //Creating my first prompt and and calling it "initprompt."
  var initPrompt = window.prompt('How many characters would you like in your password?')
  
  //Turning the value of the init prompt into a number using "parseint."
  var charLength = parseInt(initPrompt)
  
  /* Creating a funcction that makes it so that if anything other than a number is inputted, then
  an alert occurs and they are returned.*/
  if (isNaN(charLength)){
   window.alert("Invalid Entry.")
   return
  }
  /* Creating a function that makes it so that if the value of the number inputted is above 128 or below
  8, then another alert occurs and they are returned.*/
  if (charLength < 8 || charLength > 128){ 
    window.alert("Password length must be between 8-128 characters")
    return
  }
  //Creating prompts that only gives a true or false statement to the question asked using the
  //"windows.confirm" method.
  var intPrompt = window.confirm("Would you like numbers in your password?");
  var upperPrompt = window.confirm("Would you like uppercase letters in your password?");
  var lowerPrompt = window.confirm("Would you like lowercase letters in your password?");
  var symbolPrompt = window.confirm("Would you like symbols in your password?");
  
  var integerGen = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",];
  var lowerGen = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",];
  var upperGen = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",];
  var symbolGen = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",];
  
  selectedPrompts = []
  
  /*This "if" statement ensures that if the intPrompt is confirmed to be true, then the integerGen function
  will be pushed into the selected prompts array as one of the selected prompts.*/
  if (intPrompt === true){
    selectedPrompts.push(integerGen)
  
  }
    /*This "if" statement ensures that if the upperPrompt is confirmed to be true, then the upperGen function
  will be pushed into the selected prompts array as one of the selected prompts.*/ 
  
  if (upperPrompt === true){
    selectedPrompts.push(upperGen)
    
  }
  /*This "if" statement ensures that if the lowerPrompt is confirmed to be true, then the lowerGen function
  will be pushed into the selected prompts array as one of the selected prompts.*/
  
  if (lowerPrompt === true){
    selectedPrompts.push(lowerGen)
    
    /*This "if" statement ensures that if the symbolPrompt is confirmed to be true, then the symbolGen function
  will be pushed into the selected prompts array as one of the selected prompts.*/
  }
  if (symbolPrompt === true){
    selectedPrompts.push(symbolGen)
  
  }
  
   var generatePassword= ""

  for(var i = 0; i < charLength; i++ ) {
    var randomList = randomItem(selectedPrompts)
    var randomChar = randomItem(randomList)
    console.log(randomChar)
    
  }
    
  }
  
  function writePassword() {
    var password = generatePassword();
    var passwordText = document.querySelector("#password");
    passwordText.value = password;
  }
  
  generateBtn.addEventListener("click", writePassword);
  
  
  
  
  /*This function is used to generate a random lowercase letter using the function "Math.random" 
  to generate a random number between 97 and 122 and correlate it to the charcode using 
"String.fromCharCode". I have also used the function "Math.floor" in order to round the 
integer generated by "Math.random" to the nearest full number.*/

/*function lowerGen(){
  return String.fromCharCode(Math.floor(Math.random() * 26) + 97);
  
 }

/*This function is used to generate a random uppercase letter using the function "Math.random" 
to generate a random number between 65 and 90 and to correlate it to the charcode using 
"String.fromCharCode". I have also used the function "Math.floor" in order to round the 
integer generated by "Math.random" to the nearest full number.*/

/*function upperGen(){
  return String.fromCharCode(Math.floor(Math.random() * 26) + 65);
  
}

/*This function is used to generate a random integer using the function "Math.random" 
to generate a random number between 48 and 57 to correlate it to the charcode using 
"String.fromCharCode". I have also used the function "Math.floor" in order to round the 
integer generated by "Math.random" to the nearest full number.*/

/*function integerGen(){
  return String.fromCharCode(Math.floor(Math.random() * 10) + 48);

}

/*This function is used to generate a random lowercase letter using the function "Math.random" 
to generate a random number between 97 and 122 to correlate it to the charcode using 
"String.fromCharCode". I have also used the function Math.floor in order to round the 
integer generated by Math.random to the nearest full number.*/

/*function symbolGen(){
  return String.fromCharCode(Math.floor(Math.random() * 12) + 35);

}*/

//A new array to store our selected prompts..





